language: scala

scala:
  - "2.10.5"

jdk:
  - oraclejdk7

env:
  - SPARK_VERSION=1.2.1
  - SPARK_VERSION=1.2.2
  - SPARK_VERSION=1.3.0
  - SPARK_VERSION=1.3.1
  - SPARK_VERSION=1.4.1

addons:
  apt:
    packages:
    - python-virtualenv

services:
  - cassandra

script: make clean dist test-travis

sudo: false

cache:
  directories:
    - lib
    - $HOME/.m2
